spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jerryos/test-config
server:
  port: 1201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/