server:
  port: 8762

spring:
  application:
    name: eureka-server-app-01

eureka:
  client:
    allow-redirects: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka02:8763/eureka/
  instance:
    hostname: eureka01

